//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_conv
    {
        public int id { get; set; }
        public int Message { get; set; }
        public int Sender { get; set; }
        public int Reciever { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
