//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime StartOrderDate { get; set; }
        public Nullable<System.DateTime> CloseOrderDate { get; set; }
        public int SummaryPrice { get; set; }
        public int CurrentPayments { get; set; }
        public bool isClose { get; set; }
    }
}
