//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEditHistory
    {
        public int id { get; set; }
        public int productId { get; set; }
        public System.DateTime edytingDate { get; set; }
        public string productName { get; set; }
        public string productPrice { get; set; }
        public string productCategory { get; set; }
        public string productPV { get; set; }
    }
}
